version: '3.8'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: testPassword
      POSTGRES_DB: testdb
    ports:
      - 5499:5432